import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Brain,Database,Search,Upload,GitBranch,ShieldCheck,Activity,Settings,Users,KeyRound,Sparkles,RefreshCw,AlertTriangle,Copy,HeartPulse,Archive,ArrowUpCircle,Network,BookOpen,FileText,Eye,Play,CheckCircle2,XCircle,ChevronRight,Menu,X}from'lucide-react';
import'./styles.css';

const DEFAULT_BASE=import.meta.env.VITE_MEMORYX_API_BASE_URL||'http://127.0.0.1:8000';
const store={get:k=>localStorage.getItem(k)||'',set:(k,v)=>localStorage.setItem(k,v)};
function apiConfig(){return{base:store.get('mx_base')||DEFAULT_BASE,token:store.get('mx_token'),tenant:store.get('mx_tenant')||'tenant_dev'}}
async function request(path,{method='GET',body,form,rootSecret}={}){const c=apiConfig();const h={};if(c.token)h.Authorization=`Bearer ${c.token.replace(/^Bearer\s+/i,'')}`;if(c.tenant)h['x-tenant-id']=c.tenant;if(rootSecret)h['X-Root-Secret']=rootSecret;if(body!==undefined)h['Content-Type']='application/json';const r=await fetch(c.base+path,{method,headers:h,body:form||body!==undefined?form||JSON.stringify(body):undefined});let data;try{data=await r.json()}catch{data=await r.text()}if(!r.ok)throw new Error(typeof data==='string'?data:(data?.detail?JSON.stringify(data.detail):JSON.stringify(data)));return data}
const post=(p,b)=>request(p,{method:'POST',body:b});
const safe=(o,paths,f='—')=>{for(const p of paths){let v=p.split('.').reduce((a,k)=>a?.[k],o);if(v!==undefined&&v!==null&&v!=='')return v}return f};
const arr=(o,paths=[])=>{for(const p of paths){const v=p.split('.').reduce((a,k)=>a?.[k],o);if(Array.isArray(v))return v}return[]};
const pct=v=>v===undefined||v===null?'—':`${Math.round((Number(v)<=1?Number(v)*100:Number(v)))}%`;
function useApi(){const[loading,setLoading]=useState(false),[error,setError]=useState('');const run=async fn=>{setLoading(true);setError('');try{return await fn()}catch(e){setError(e.message);throw e}finally{setLoading(false)}};return{loading,error,run,setError}}
const nav=[['Overview','overview',Brain],['MEMORY'],['Explorer','memory',Database],['Search','search',Search],['Upload / Create','upload',Upload],['Lineage','lineage',GitBranch],['INTELLIGENCE'],['Overview','intelligence',Sparkles],['Health & Quality','health',HeartPulse],['Duplicates','duplicates',Copy],['Conflicts','conflicts',AlertTriangle],['Knowledge Gaps','gaps',BookOpen],['Impact / Policies','policies',Network],['Promotion','promotion',ArrowUpCircle],['Archival','archival',Archive],['Recommendations','recommendations',CheckCircle2],['COGNITION'],['Cognitive Workspace','cognitive',Sparkles],['Context Assembly','context',FileText],['Reflection & Learning','reflection',Brain],['METAMEMORY'],['Topics & Signals','metamemory',Network],['Summaries & Lifecycle','lifecycle',RefreshCw],['GOVERNANCE'],['Approval Center','approvals',ShieldCheck],['Ethics & PII','ethics',ShieldCheck],['Audit Trail','audit',Eye],['OBSERVABILITY'],['Telemetry','telemetry',Activity],['ADMINISTRATION'],['Tenants & Users','admin',Users],['API Keys','keys',KeyRound],['System','system',Settings]];
function Card({title,value,sub,onClick}){return <button className="metric" onClick={onClick}><small>{title}</small><b>{value??'—'}</b><span>{sub||'Not evaluated'}</span></button>}
function Json({data}){return <pre className="json">{data===undefined?'No API response yet.':JSON.stringify(data,null,2)}</pre>}
function Banner({error,loading}){return <>{loading&&<div className="banner info">Calling MemoryX API…</div>}{error&&<div className="banner error">{error}</div>}</>}
function Empty({text='No data returned by the API.'}){return <div className="empty">{text}</div>}
function Shell(){const[route,setRoute]=useState(location.hash.slice(1)||'overview'),[mobile,setMobile]=useState(false);useEffect(()=>{const f=()=>setRoute(location.hash.slice(1)||'overview');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const go=r=>{location.hash=r;setMobile(false)};return <div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="logo">M</div><div><b>MemoryX</b><small>Enterprise Cognitive Memory Platform</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map((n,i)=>n.length===1?<div className="navhead" key={i}>{n[0]}</div>:(()=>{const I=n[2];return <button key={i} className={route===n[1]?'active':''} onClick={()=>go(n[1])}><I size={17}/>{n[0]}</button>})())}</nav></aside><main><Topbar onMenu={()=>setMobile(true)}/><div className="page"><Router route={route} go={go}/></div></main></div>}
function Topbar({onMenu}){const[tenant,setTenant]=useState(apiConfig().tenant);return <header><button className="menub" onClick={onMenu}><Menu/></button><div className="global"><Search size={17}/><input placeholder="Search memories, topics, or ask MemoryX…" onKeyDown={e=>{if(e.key==='Enter'){sessionStorage.setItem('mx_query',e.currentTarget.value);location.hash='search'}}}/></div><input className="tenant" value={tenant} onChange={e=>{setTenant(e.target.value);store.set('mx_tenant',e.target.value)}}/><span className="healthy">● API configured</span></header>}
function Router({route,go}){const map={overview:<Overview go={go}/>,memory:<MemoryExplorer go={go}/>,search:<SearchPage/>,upload:<UploadPage/>,lineage:<Lineage/>,intelligence:<Intelligence go={go}/>,health:<Health/>,duplicates:<Duplicates/>,conflicts:<Conflicts/>,gaps:<Gaps/>,policies:<Policies/>,promotion:<Policies mode="promotion"/>,archival:<Policies mode="archival"/>,recommendations:<Recommendations/>,cognitive:<Cognitive/>,context:<Context/>,reflection:<Reflection/>,metamemory:<MetaMemory/>,lifecycle:<Lifecycle/>,approvals:<Recommendations approvals/>,ethics:<Ethics/>,audit:<Audit/>,telemetry:<Telemetry/>,admin:<Admin/>,keys:<Keys/>,system:<System/>};return map[route]||map.overview}
function Title({title,sub,action}){return <div className="title"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Overview({go}){const[data,setData]=useState(),[stats,setStats]=useState();const a=useApi();const load=()=>a.run(async()=>{const [s,i]=await Promise.allSettled([request('/v1/memory/stats'),post('/v1/memory-intelligence/run',{tenant_id:apiConfig().tenant,options:{detect_duplicates:true,detect_conflicts:true,analyze_gaps:true,analyze_impact:true,calculate_health:true,evaluate_promotion:true,evaluate_archival:true,generate_recommendations:true,generate_optimization_plan:true,execute_approved_actions:false}})]);if(s.status==='fulfilled')setStats(s.value);if(i.status==='fulfilled')setData(i.value);if(s.status==='rejected'&&i.status==='rejected')throw i.reason});useEffect(()=>{load().catch(()=>{})},[]);const sum=data?.summary||data?.intelligence_summary||{};return <><Title title="Memory Intelligence Overview" sub="Monitor, understand and evolve enterprise memory" action={<button onClick={()=>load().catch(()=>{})}><RefreshCw size={16}/> Refresh</button>}/><Banner {...a}/><div className="metrics"><Card title="Total Memories" value={safe(sum,['memory_count'],safe(stats||{},['total','count','total_memories']))} onClick={()=>go('memory')}/><Card title="Memory Health" value={pct(safe(sum,['overall_health_score'],null))} onClick={()=>go('health')}/><Card title="Duplicates" value={safe(sum,['duplicate_count'])} onClick={()=>go('duplicates')}/><Card title="Conflicts" value={safe(sum,['conflict_count'])} onClick={()=>go('conflicts')}/><Card title="Knowledge Gaps" value={safe(sum,['gap_count'])} onClick={()=>go('gaps')}/><Card title="Promotion Candidates" value={safe(sum,['promotion_candidate_count'])} onClick={()=>go('promotion')}/><Card title="Archival Candidates" value={safe(sum,['archival_candidate_count'])} onClick={()=>go('archival')}/><Card title="Risk Level" value={safe(sum,['risk_level'])}/></div><div className="grid2"><section><h3>Intelligence Recommendations</h3><RecommendationList data={arr(data,['recommendations'])}/></section><section><h3>System / Stats</h3><Json data={stats}/></section></div><AskBox/></>}
function AskBox(){const[q,setQ]=useState('');return <section className="ask"><Sparkles/><div><h3>Ask MemoryX</h3><p>Use enterprise memory to reason over knowledge.</p><div className="row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask anything about enterprise knowledge…"/><button onClick={()=>{sessionStorage.setItem('mx_cognitive_query',q);location.hash='cognitive'}}>Run <ChevronRight size={16}/></button></div></div></section>}
function MemoryExplorer({go}){const[q,setQ]=useState(''),[data,setData]=useState(),[selected,setSelected]=useState();const a=useApi();const load=(query='')=>a.run(async()=>setData(await post('/v1/memory/search',{query,limit:100})));useEffect(()=>{load('').catch(()=>{})},[]);const items=arr(data,['records','items','memories','results']);return <><Title title="Memory Explorer" sub="Browse and manage enterprise memory" action={<div className="row"><button onClick={()=>go('upload')}>+ Create / Upload</button><button onClick={()=>load(q).catch(()=>{})}>Refresh</button></div>}/><Banner {...a}/><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q).catch(()=>{})} placeholder="Search title, content, tag or ID…"/><button onClick={()=>load(q).catch(()=>{})}><Search size={16}/> Search</button></div>{items.length?<div className="table">{items.map((m,i)=><button className="tr" key={safe(m,['id','memory_id'],i)} onClick={()=>setSelected(m)}><span><b>{safe(m,['title','content','text','id'],'Memory')}</b><small>{safe(m,['id','memory_id'],'')}</small></span><span>{safe(m,['memory_type','type'])}</span><span>{safe(m,['state','tier'])}</span><ChevronRight/></button>)}</div>:<Empty/>}{selected&&<div className="drawer"><button className="x" onClick={()=>setSelected(null)}><X/></button><h2>{safe(selected,['title','id'],'Memory')}</h2><Json data={selected}/><button onClick={()=>{sessionStorage.setItem('mx_memory_id',safe(selected,['id','memory_id'],''));go('lineage')}}>View Lineage</button></div>}</>}
function SearchPage(){const[q,setQ]=useState(sessionStorage.getItem('mx_query')||''),[mode,setMode]=useState('search'),[data,setData]=useState();const a=useApi();const run=()=>a.run(async()=>setData(await post(mode==='vector'?'/v1/memory/vector_search':'/v1/memory/search',mode==='vector'?{query:q,top_k:20}:{query:q,limit:20})));return <><Title title="Memory Search" sub="Semantic and vector retrieval over enterprise memory"/><div className="tabs"><button className={mode==='search'?'on':''} onClick={()=>setMode('search')}>Semantic</button><button className={mode==='vector'?'on':''} onClick={()=>setMode('vector')}>Vector</button></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search enterprise knowledge…"/><button onClick={()=>run().catch(()=>{})}>Search</button></div><Banner {...a}/><Json data={data}/></>}
function UploadPage(){const[file,setFile]=useState(),[type,setType]=useState('episodic'),[modality,setModality]=useState('document'),[data,setData]=useState();const a=useApi();const upload=()=>a.run(async()=>{if(!file)throw Error('Choose a file first.');const f=new FormData();f.append('file',file);const c=apiConfig(),h={Authorization:`Bearer ${c.token.replace(/^Bearer\s+/i,'')}`,'x-tenant-id':c.tenant};const r=await fetch(`${c.base}/v1/memory/upload?modality=${modality}&memory_type=${type}`,{method:'POST',headers:h,body:f});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));setData(d)});return <><Title title="Upload / Create Memory" sub="Ingest document, image, audio or video memory"/><section className="form"><label>File<input type="file" onChange={e=>setFile(e.target.files?.[0])}/></label><label>Modality<select value={modality} onChange={e=>setModality(e.target.value)}>{['document','image','audio','video'].map(x=><option>{x}</option>)}</select></label><label>Memory Type<select value={type} onChange={e=>setType(e.target.value)}>{['episodic','semantic','procedural','short_term'].map(x=><option>{x}</option>)}</select></label><button onClick={()=>upload().catch(()=>{})}><Upload size={16}/> Upload</button></section><Banner {...a}/><Json data={data}/></>}
function Lineage(){const[id,setId]=useState(sessionStorage.getItem('mx_memory_id')||''),[data,setData]=useState();const a=useApi();const run=()=>a.run(async()=>setData(await request(`/v1/memory/${encodeURIComponent(id)}/lineage`)));return <><Title title="Memory Lineage" sub="Inspect provenance and relationships"/><div className="toolbar"><input value={id} onChange={e=>setId(e.target.value)} placeholder="Memory ID"/><button onClick={()=>run().catch(()=>{})}>Load Lineage</button></div><Banner {...a}/><Json data={data}/></>}
function Intelligence({go}){const[data,setData]=useState();const a=useApi();const run=()=>a.run(async()=>setData(await post('/v1/memory-intelligence/run',{tenant_id:apiConfig().tenant,options:{detect_duplicates:true,detect_conflicts:true,analyze_gaps:true,analyze_impact:true,calculate_health:true,evaluate_promotion:true,evaluate_archival:true,generate_recommendations:true,generate_optimization_plan:true,execute_approved_actions:false}})));return <><Title title="Memory Intelligence" sub="Quality, conflicts, gaps, lifecycle and recommendations" action={<button onClick={()=>run().catch(()=>{})}><Play size={16}/> Run Analysis</button>}/><Banner {...a}/>{data?<><div className="metrics"><Card title="Health" value={pct(safe(data,['summary.overall_health_score']))} onClick={()=>go('health')}/><Card title="Duplicates" value={safe(data,['summary.duplicate_count'])} onClick={()=>go('duplicates')}/><Card title="Conflicts" value={safe(data,['summary.conflict_count'])} onClick={()=>go('conflicts')}/><Card title="Gaps" value={safe(data,['summary.gap_count'])} onClick={()=>go('gaps')}/></div><Json data={data}/></>:<Empty text="Run Memory Intelligence to populate this workspace."/>}</>}
function ToolPage({title,sub,path,initial}){const[data,setData]=useState();const[raw,setRaw]=useState(JSON.stringify(initial||{tenant_id:apiConfig().tenant},null,2));const a=useApi();const run=()=>a.run(async()=>setData(await post(path,JSON.parse(raw))));return <><Title title={title} sub={sub} action={<button onClick={()=>run().catch(()=>{})}><Play size={16}/> Run</button>}/><Banner {...a}/><div className="grid2"><section><h3>Request</h3><textarea className="codeinput" value={raw} onChange={e=>setRaw(e.target.value)}/></section><section><h3>Response</h3><Json data={data}/></section></div></>}
const Health=()=> <ToolPage title="Health & Quality" sub="Analyze memory health" path="/v1/memory-intelligence/health-analysis" initial={{tenant_id:apiConfig().tenant,memory_ids:[],limit:100}}/>;
const Duplicates=()=> <ToolPage title="Duplicate Intelligence" sub="Detect exact, semantic and near-duplicate memories" path="/v1/memory-intelligence/duplicates" initial={{tenant_id:apiConfig().tenant,memory_ids:[],limit:100}}/>;
const Conflicts=()=> <ToolPage title="Conflict Intelligence" sub="Detect conflicting enterprise memories" path="/v1/memory-intelligence/conflicts" initial={{tenant_id:apiConfig().tenant,memory_ids:[],limit:100}}/>;
function Gaps(){return <Intelligence/>}
function Policies({mode}){const promotion=mode!=='archival';return <ToolPage title={promotion?'Promotion Policy':'Archival Policy'} sub="Evaluate lifecycle policy candidates" path={promotion?'/v1/memory-intelligence/promotion-policy':'/v1/memory-intelligence/archival-policy'} initial={{tenant_id:apiConfig().tenant,memory_ids:[],limit:100}}/>}
function RecommendationList({data}){return data?.length?<div className="recs">{data.map((r,i)=><div className="rec" key={r.recommendation_id||i}><span className="badge">{safe(r,['priority'])}</span><b>{safe(r,['title'])}</b><p>{safe(r,['description'])}</p><small>Confidence {pct(r.confidence)} • {r.requires_approval?'Approval required':'No approval required'}</small></div>)}</div>:<Empty text="No recommendations returned."/>}
function Recommendations({approvals}){const[id,setId]=useState(''),[approved,setApproved]=useState(false),[data,setData]=useState();const a=useApi();const execute=()=>a.run(async()=>setData(await post('/v1/memory-intelligence/recommendations/execute',{tenant_id:apiConfig().tenant,recommendation_id:id,approved})));return <><Title title={approvals?'Approval Center':'Recommendation Execution'} sub="Human-governed execution of intelligence recommendations"/><section className="form"><label>Recommendation ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label className="check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> Approved</label><button onClick={()=>execute().catch(()=>{})}>Execute</button></section><Banner {...a}/><Json data={data}/></>}
function Cognitive(){const[q,setQ]=useState(sessionStorage.getItem('mx_cognitive_query')||''),[goal,setGoal]=useState(''),[mode,setMode]=useState('assistant'),[policy,setPolicy]=useState('auto'),[data,setData]=useState();const a=useApi();const run=()=>a.run(async()=>setData(await post('/v1/cognitive/kernel/run',{query:q,goal:goal||null,model_policy:policy,mode,context_ids:[],constraints:{},enable_ethics:true,auto_learn:true,auto_reflect:true,run_lifecycle_after_reflection:true})));return <><Title title="Cognitive Workspace" sub="Reason across enterprise memory with reflection, learning and governance"/><section className="form"><label>Query<textarea value={q} onChange={e=>setQ(e.target.value)}/></label><label>Goal<input value={goal} onChange={e=>setGoal(e.target.value)}/></label><div className="row"><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>assistant</option><option>planner</option><option>auto</option></select></label><label>Model Policy<select value={policy} onChange={e=>setPolicy(e.target.value)}>{['auto','high_quality','fast','cheap'].map(x=><option>{x}</option>)}</select></label></div><button onClick={()=>run().catch(()=>{})}><Sparkles size={16}/> Run Cognitive Kernel</button></section><Banner {...a}/>{data&&<div className="journey"><span>Understand ✓</span><span>Memory ✓</span><span>Context ✓</span><span>Reason ✓</span><span>Governance ✓</span><span>Reflect ✓</span><span>Learn ✓</span></div>}<Json data={data}/></>}
const Context=()=> <ToolPage title="Context Assembly" sub="Build a context pack from MemoryX" path="/v1/context/assemble" initial={{query:'',context_ids:[]}}/>;
function Reflection(){return <><ToolPage title="Reflection" sub="Commit execution reflection" path="/v1/reflection/commit" initial={{outcome:'success',metrics:{},surprises:[],delta_facts:[],lessons:[]}}/><ToolPage title="Learning" sub="Record an explicit learning signal" path="/v1/learn/record" initial={{}}/></>}
function MetaMemory(){const[topics,setTopics]=useState(),[signals,setSignals]=useState();const a=useApi();const run=()=>a.run(async()=>{const[t,s]=await Promise.all([request('/v1/metamemory/topics'),request('/v1/metamemory/signals')]);setTopics(t);setSignals(s)});return <><Title title="MetaMemory" sub="Topics, signals and higher-order memory structure" action={<button onClick={()=>run().catch(()=>{})}>Load</button>}/><Banner {...a}/><div className="grid2"><section><h3>Topics</h3><Json data={topics}/></section><section><h3>Signals</h3><Json data={signals}/></section></div></>}
function Lifecycle(){const[data,setData]=useState();const a=useApi();const run=p=>a.run(async()=>setData(await request(p,{method:'POST'})));return <><Title title="Summaries & Lifecycle" sub="Run MetaMemory summarization and lifecycle evolution"/><div className="row"><button onClick={()=>run('/v1/metamemory/summarize').catch(()=>{})}>Run Summarizer</button><button onClick={()=>run('/v1/admin/lifecycle/run').catch(()=>{})}>Run Lifecycle</button></div><Banner {...a}/><Json data={data}/></>}
function Ethics(){const[text,setText]=useState(''),[data,setData]=useState(),[pii,setPii]=useState();const a=useApi();return <><Title title="Ethics & PII" sub="Assess content and inspect tenant PII signals"/><section className="form"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Text to assess"/><div className="row"><button onClick={()=>a.run(async()=>setData(await post('/v1/ethics/assess',{text,context_ids:[],policy:'default_v1'}))).catch(()=>{})}>Assess Ethics</button><button onClick={()=>a.run(async()=>setPii(await request('/v1/admin/pii-scan?limit=500'))).catch(()=>{})}>PII Scan</button></div></section><Banner {...a}/><div className="grid2"><Json data={data}/><Json data={pii}/></div></>}
function Audit(){const[data,setData]=useState();const a=useApi();return <><Title title="Audit Trail" sub="MetaMemory audit logs" action={<button onClick={()=>a.run(async()=>setData(await request('/v1/metamemory/audit/logs'))).catch(()=>{})}>Load Logs</button>}/><Banner {...a}/><Json data={data}/></>}
function Telemetry(){const[data,setData]=useState();const a=useApi();return <><Title title="Telemetry" sub="Runtime observability" action={<button onClick={()=>a.run(async()=>setData(await request('/v1/telemetry/peek'))).catch(()=>{})}>Refresh</button>}/><Banner {...a}/><Json data={data}/></>}
function Admin(){const[data,setData]=useState();const a=useApi();return <><Title title="Tenants & Users" sub="Administrative tenant workspace"/><div className="row"><button onClick={()=>a.run(async()=>setData(await request('/v1/admin/tenants'))).catch(()=>{})}>List Tenants</button><button onClick={()=>a.run(async()=>setData(await request('/v1/auth/me'))).catch(()=>{})}>Current User</button></div><Banner {...a}/><Json data={data}/></>}
function Keys(){return <ToolPage title="API Keys" sub="Create tenant API keys" path="/v1/admin/api_keys" initial={{label:'MemoryX UI',tenant_id:apiConfig().tenant}}/>}
function System(){const[c,setC]=useState(apiConfig()),[saved,setSaved]=useState(false),[health,setHealth]=useState();const a=useApi();const save=()=>{store.set('mx_base',c.base);store.set('mx_token',c.token);store.set('mx_tenant',c.tenant);setSaved(true);setTimeout(()=>setSaved(false),1500)};return <><Title title="System Configuration" sub="Connect this UI to your real MemoryX FastAPI backend"/><section className="form"><label>API Base URL<input value={c.base} onChange={e=>setC({...c,base:e.target.value})}/></label><label>Bearer Token<input type="password" value={c.token} onChange={e=>setC({...c,token:e.target.value})}/></label><label>Tenant ID<input value={c.tenant} onChange={e=>setC({...c,tenant:e.target.value})}/></label><div className="row"><button onClick={save}>Save Connection</button><button onClick={()=>a.run(async()=>setHealth(await request('/v1/memory-intelligence/health'))).catch(()=>{})}>Test API</button>{saved&&<span className="healthy">Saved</span>}</div></section><Banner {...a}/><Json data={health}/><section className="danger"><h3>Danger Zone</h3><p>Destructive database cleanup is intentionally not exposed as a one-click action. Use the backend/admin workflow with explicit confirmation.</p></section></>}
createRoot(document.getElementById('root')).render(<Shell/>);
